### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by glerinsonum** [shihabmridha/instagram-image-viewer#1]
@shihabmridha How I can use this product. Tell with an video. installation

**Comment by shihabmridha** [comment]
Install nodejs. Clone this project  to your computer. Open cmd from the root folder. Type "npm install" and press enter to install required modules. Finally type "node app.js" and press enter. App will run on port 3000 in localhost.

**Comment by glerinsonum** [comment]
@shihabmridha Cordially thank you. 
With this app can I see more photos of any someone using username. :)

**Comment by shihabmridha** [comment]
No. You can see only public photos using url.

**Comment by glerinsonum** [comment]
@shihabmridha Brother. How I can integrate this script this plugin as transform into Maltego. 
Tell me with one video. Cordially thank you.

**Comment by glerinsonum** [comment]
@shihabmridha can i see instagram message of my friend. ?
